=== Geonovum/xml_omgevingsplan_gemeentestad/xsd-1.0-concept/bestanden-ow/generiek/manifest-ow.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Modules">
    <xs:annotation>
      <xs:documentation>Root element van CIM-OW.xml.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="1" ref="domein"/>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="RegelingVersie"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="domein">
    <xs:annotation>
      <xs:documentation>Het domein geeft het wetgevingsdomein aan en is nodig om de verwerking in de keten beter te laten verlopen. Het element een vaste waarde "omgevingswet".</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value="omgevingswet"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="RegelingVersie">
    <xs:annotation>
      <xs:documentation>CIM-OW bestanden die horen bij een specifieke versie van een regeling.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="1" ref="Doel"/>
        <xs:element maxOccurs="1" minOccurs="0" ref="VoorgaandDoel"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="Bestand">
          <xs:annotation>
            <xs:documentation>Bestandsnaam van de module volgens CIM-OW opmaak. Het bestand moet ook in de manifest voorkomen.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Doel" type="xs:anyURI">
    <xs:annotation>
      <xs:documentation>Verwijzing naar Doel van het besluit.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="VoorgaandDoel" type="xs:anyURI">
    <xs:annotation>
      <xs:documentation>Verwijzing naar het voorgaande Doel.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="Bestand">
    <xs:annotation>
      <xs:documentation>Basistype voor alle leveringen via Digikoppeling ebMS.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="1" ref="naam"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="objecttype"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="naam" type="xs:NCName">
    <xs:annotation>
      <xs:documentation>Naam van het bestand; moet overeenkomen met de naam zoals in manifest.xml is opgenomen.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="objecttype" type="xs:string">
    <xs:annotation>
      <xs:documentation>Type van de objecten die in het bestand voorkomen. De toegestane waarde voor het objecttype is beschreven in de CIM-OW documentatie.</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>

=== Geonovum/xml_omgevingsplan_gemeentestad/opdracht_10/manifest-ow.xml
<?xml version="1.0" encoding="utf-8"?>
<Modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://www.geostandaarden.nl/imow ../../../xsd/imow/bestanden-ow/generiek/v20190901/manifest-ow.xsd">
  <domein>omgevingswet</domein>
  <RegelingVersie>
    <Doel>/join/id/proces/gm0297/2019/Instelling</Doel>
    <Bestand>
      <naam>owActiviteiten-Gemeentestad.xml</naam>
      <objecttype>Activiteit</objecttype>
    </Bestand>
    <Bestand>
      <naam>owLocaties-Gemeentestad.xml</naam>
      <objecttype>Gebied</objecttype>
    </Bestand>
    <Bestand>
      <naam>owRegeltekst-Gemeentestad.xml</naam>
      <objecttype>Regeltekst</objecttype>
      <objecttype>RegelVoorIedereen</objecttype>
    </Bestand>
  </RegelingVersie>
</Modules>
